package mapping;
// Generated 14/07/2015 09:21:05 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Accesos generated by hbm2java
 */
public class Accesos implements java.io.Serializable {

    private Integer codigo;
    private String nombre;
    private String url;
    private String categoria;
    private Set usuariosAccesoses = new HashSet(0);

    public Accesos() {
    }

    public Accesos(String nombre, String url, String categoria) {
        this.nombre = nombre;
        this.url = url;
        this.categoria = categoria;
    }

    public Accesos(String nombre, String url, String categoria, Set usuariosAccesoses) {
        this.nombre = nombre;
        this.url = url;
        this.categoria = categoria;
        this.usuariosAccesoses = usuariosAccesoses;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getCategoria() {
        return this.categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    public Set getUsuariosAccesoses() {
        return this.usuariosAccesoses;
    }

    public void setUsuariosAccesoses(Set usuariosAccesoses) {
        this.usuariosAccesoses = usuariosAccesoses;
    }

    @Override
    public String toString() {
        return String.format("%s", nombre);
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Accesos)) {
            return false;
        }
        Accesos acceso = (Accesos) obj;
        return (Objects.equals(this.codigo, acceso.codigo));
    }

}
