package mapping;
// Generated 24-may-2015 21:47:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CuentasXPagar generated by hbm2java
 */
public class CuentasXPagar  implements java.io.Serializable {


     private Integer codigo;
     private OrdenesCompra ordenesCompra;
     private Date fecha;
     private BigDecimal importe;
     private String observaciones;
     private String estatus;
     private Set<AbonosCuentasXPagar> abonosCuentasXPagars = new HashSet<AbonosCuentasXPagar>(0);

    public CuentasXPagar() {
    }

	
    public CuentasXPagar(OrdenesCompra ordenesCompra, Date fecha, BigDecimal importe, String estatus) {
        this.ordenesCompra = ordenesCompra;
        this.fecha = fecha;
        this.importe = importe;
        this.estatus = estatus;
    }
    public CuentasXPagar(OrdenesCompra ordenesCompra, Date fecha, BigDecimal importe, String observaciones, String estatus, Set<AbonosCuentasXPagar> abonosCuentasXPagars) {
       this.ordenesCompra = ordenesCompra;
       this.fecha = fecha;
       this.importe = importe;
       this.observaciones = observaciones;
       this.estatus = estatus;
       this.abonosCuentasXPagars = abonosCuentasXPagars;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public OrdenesCompra getOrdenesCompra() {
        return this.ordenesCompra;
    }
    
    public void setOrdenesCompra(OrdenesCompra ordenesCompra) {
        this.ordenesCompra = ordenesCompra;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public Set<AbonosCuentasXPagar> getAbonosCuentasXPagars() {
        return this.abonosCuentasXPagars;
    }
    
    public void setAbonosCuentasXPagars(Set<AbonosCuentasXPagar> abonosCuentasXPagars) {
        this.abonosCuentasXPagars = abonosCuentasXPagars;
    }




}


