package mapping;
// Generated 24-may-2015 21:47:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer codigo;
     private TipoProducto tipoProducto;
     private UnidadesDeMedida unidadesDeMedida;
     private String descripcion;
     private boolean incluyeVicera;
     private boolean generarSubproducto;
     private boolean aplicaInventarioFisico;
     private String estatus;
     private BigDecimal precioSugerido;
     private Subfamilias subfamilias;
     private Set<Productos> productosesForProductosCodigoPadre = new HashSet<Productos>(0);
     private Set<Productos> productosesForProductosCodigoHijo = new HashSet<Productos>(0);
     private Set<ProductosHasProveedores> productosHasProveedoreses = new HashSet<ProductosHasProveedores>(0);
     private boolean ProductoPesado;
     

    public Productos() {
    }

	
    public Productos(TipoProducto tipoProducto, UnidadesDeMedida unidadesDeMedida, String descripcion, boolean incluyeVicera, boolean generarSubproducto, boolean aplicaInventarioFisico, String estatus, BigDecimal precioSugerido) {
        this.tipoProducto = tipoProducto;
        this.unidadesDeMedida = unidadesDeMedida;
        this.descripcion = descripcion;
        this.incluyeVicera = incluyeVicera;
        this.generarSubproducto = generarSubproducto;
        this.aplicaInventarioFisico = aplicaInventarioFisico;
        this.estatus = estatus;
        this.precioSugerido = precioSugerido;
    }
    public Productos(TipoProducto tipoProducto, UnidadesDeMedida unidadesDeMedida, String descripcion, boolean incluyeVicera, boolean generarSubproducto, boolean aplicaInventarioFisico, String estatus, BigDecimal precioSugerido, Set<Productos> productosesForProductosCodigoPadre, Set<Productos> productosesForProductosCodigoHijo, Set<ProductosHasProveedores> productosHasProveedoreses) {
       this.tipoProducto = tipoProducto;
       this.unidadesDeMedida = unidadesDeMedida;
       this.descripcion = descripcion;
       this.incluyeVicera = incluyeVicera;
       this.generarSubproducto = generarSubproducto;
       this.aplicaInventarioFisico = aplicaInventarioFisico;
       this.estatus = estatus;
       this.precioSugerido = precioSugerido;
       this.productosesForProductosCodigoPadre = productosesForProductosCodigoPadre;
       this.productosesForProductosCodigoHijo = productosesForProductosCodigoHijo;
       this.productosHasProveedoreses = productosHasProveedoreses;
    }

    public boolean isProductoPesado() {
        return ProductoPesado;
    }

    public void setProductoPesado(boolean ProductoPesado) {
        this.ProductoPesado = ProductoPesado;
    }
    
    
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public TipoProducto getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    public UnidadesDeMedida getUnidadesDeMedida() {
        return this.unidadesDeMedida;
    }
    
    public void setUnidadesDeMedida(UnidadesDeMedida unidadesDeMedida) {
        this.unidadesDeMedida = unidadesDeMedida;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isIncluyeVicera() {
        return this.incluyeVicera;
    }
    
    public void setIncluyeVicera(boolean incluyeVicera) {
        this.incluyeVicera = incluyeVicera;
    }
    public boolean isGenerarSubproducto() {
        return this.generarSubproducto;
    }
    
    public void setGenerarSubproducto(boolean generarSubproducto) {
        this.generarSubproducto = generarSubproducto;
    }
    public boolean isAplicaInventarioFisico() {
        return this.aplicaInventarioFisico;
    }
    
    public void setAplicaInventarioFisico(boolean aplicaInventarioFisico) {
        this.aplicaInventarioFisico = aplicaInventarioFisico;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public BigDecimal getPrecioSugerido() {
        return this.precioSugerido;
    }
    
    public void setPrecioSugerido(BigDecimal precioSugerido) {
        this.precioSugerido = precioSugerido;
    }

    public Subfamilias getSubfamilias() {
        return subfamilias;
    }

    public void setSubfamilias(Subfamilias subfamilias) {
        this.subfamilias = subfamilias;
    }
    
    public Set<Productos> getProductosesForProductosCodigoPadre() {
        return this.productosesForProductosCodigoPadre;
    }
    
    public void setProductosesForProductosCodigoPadre(Set<Productos> productosesForProductosCodigoPadre) {
        this.productosesForProductosCodigoPadre = productosesForProductosCodigoPadre;
    }
    public Set<Productos> getProductosesForProductosCodigoHijo() {
        return this.productosesForProductosCodigoHijo;
    }
    
    public void setProductosesForProductosCodigoHijo(Set<Productos> productosesForProductosCodigoHijo) {
        this.productosesForProductosCodigoHijo = productosesForProductosCodigoHijo;
    }
    public Set<ProductosHasProveedores> getProductosHasProveedoreses() {
        return this.productosHasProveedoreses;
    }
    
    public void setProductosHasProveedoreses(Set<ProductosHasProveedores> productosHasProveedoreses) {
        this.productosHasProveedoreses = productosHasProveedoreses;
    }

    public String toString(){
        return this.getDescripcion();
    }
    
    public boolean equals(Object o){
        if( o != null){
        if(((o instanceof Productos) && (((Productos) o).getCodigo().equals(this.getCodigo())))){
            return true;
        }else{
            return false;
           }
        }else{
            return false;
        }
    }


}


