package mapping;
// Generated 11/11/2015 10:22:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import mapping.Productos;

/**
 * ProductosDelInventario generated by hbm2java
 */
public class ProductosDelInventario  implements java.io.Serializable {


     private Integer codigo;
     private Inventarios inventarios;
     private Productos productos;
     private BigDecimal peso;
     private String codigoBarras;
     private String estatus;

    public ProductosDelInventario() {
    }

	
    public ProductosDelInventario(Inventarios inventarios, Productos productos) {
        this.inventarios = inventarios;
        this.productos = productos;
    }
    public ProductosDelInventario(Inventarios inventarios, Productos productos, BigDecimal peso, String codigoBarras, String estatus) {
       this.inventarios = inventarios;
       this.productos = productos;
       this.peso = peso;
       this.codigoBarras = codigoBarras;
       this.estatus = estatus;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Inventarios getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Inventarios inventarios) {
        this.inventarios = inventarios;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public BigDecimal getPeso() {
        return this.peso;
    }
    
    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }
    public String getCodigoBarras() {
        return this.codigoBarras;
    }
    
    public void setCodigoBarras(String codigoBarras) {
        this.codigoBarras = codigoBarras;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }




}


