package mapping;
// Generated 24-may-2015 21:47:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tranferencias generated by hbm2java
 */
public class Tranferencias  implements java.io.Serializable {


     private Integer codigo;
     private Ubicaciones ubicacionesByDestino;
     private Ubicaciones ubicacionesBySalida;
     private Usuarios usuarios;
     private String estatus;
     private Date fechaEnvio;
     private Date fechaLlegada;
     private Set<ProductosInventario> productosInventarios = new HashSet<ProductosInventario>(0);
     private Set<Mermas> mermas = new HashSet<Mermas>(0);

    public Tranferencias() {
    }

	
    public Tranferencias(Ubicaciones ubicacionesByDestino, Ubicaciones ubicacionesBySalida, Usuarios usuarios, String estatus, Date fechaEnvio) {
        this.ubicacionesByDestino = ubicacionesByDestino;
        this.ubicacionesBySalida = ubicacionesBySalida;
        this.usuarios = usuarios;
        this.estatus = estatus;
        this.fechaEnvio = fechaEnvio;
    }
    public Tranferencias(Ubicaciones ubicacionesByDestino, Ubicaciones ubicacionesBySalida, Usuarios usuarios, String estatus, Date fechaEnvio, Date fechaLlegada, Set<ProductosInventario> productosInventarios) {
       this.ubicacionesByDestino = ubicacionesByDestino;
       this.ubicacionesBySalida = ubicacionesBySalida;
       this.usuarios = usuarios;
       this.estatus = estatus;
       this.fechaEnvio = fechaEnvio;
       this.fechaLlegada = fechaLlegada;
       this.productosInventarios = productosInventarios;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Ubicaciones getUbicacionesByDestino() {
        return this.ubicacionesByDestino;
    }
    
    public void setUbicacionesByDestino(Ubicaciones ubicacionesByDestino) {
        this.ubicacionesByDestino = ubicacionesByDestino;
    }
    public Ubicaciones getUbicacionesBySalida() {
        return this.ubicacionesBySalida;
    }
    
    public void setUbicacionesBySalida(Ubicaciones ubicacionesBySalida) {
        this.ubicacionesBySalida = ubicacionesBySalida;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    public Date getFechaLlegada() {
        return this.fechaLlegada;
    }
    
    public void setFechaLlegada(Date fechaLlegada) {
        this.fechaLlegada = fechaLlegada;
    }
    public Set<ProductosInventario> getProductosInventarios() {
        return this.productosInventarios;
    }
    
    public void setProductosInventarios(Set<ProductosInventario> productosInventarios) {
        this.productosInventarios = productosInventarios;
    }

    public Set<Mermas> getMermas() {
        return mermas;
    }

    public void setMermas(Set<Mermas> mermas) {
        this.mermas = mermas;
    }

    public BigDecimal getPesoTotal(){
        BigDecimal pesoTotal = new BigDecimal("0.00");
        for(ProductosInventario producto : this.productosInventarios){
            pesoTotal = pesoTotal.add(producto.getPeso());
        }
        return pesoTotal;
    }
    
    public BigDecimal getMermaTotal(){
        BigDecimal mermaTotal = new BigDecimal("0.00");
        for(Mermas merma : this.mermas){
            mermaTotal = mermaTotal.add(merma.getPeso());
        }
        return mermaTotal;
    }


}


