/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import java.awt.ComponentOrientation;
import java.math.BigDecimal;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTextField;
import listeners.NumericKeyListener;
import pesable.PesableBarCodeable;
import threads.PesoThread;

/**
 *
 * @author Administrador
 */
public class BasculaPanel extends PesableBarCodeable {

    /**
     * Creates new form BasculaPanel
     */
    public BasculaPanel() {
        
    }
    
    public void init(){
      initComponents();
        try {
            setPesoThread(new PesoThread());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error al leer el peso de la bascula", "Error", ERROR_MESSAGE);
            pesoManualChk.setSelected(true);
            pesoManualChk.setEnabled(false);
            pesoBasculaLbl.setEnabled(false);
            pesoManualTxt.setEnabled(true);
            return;
        }
        getPesoThread().setPesoLbl(pesoBasculaLbl);
        Thread thread = new Thread(getPesoThread());
        thread.start();  
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesoBasculaLbl = new javax.swing.JLabel();
        pesoManualTxt = new javax.swing.JTextField();
        pesoManualChk = new javax.swing.JCheckBox();

        pesoBasculaLbl.setBackground(new java.awt.Color(0, 0, 0));
        pesoBasculaLbl.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        pesoBasculaLbl.setForeground(new java.awt.Color(0, 255, 0));
        pesoBasculaLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pesoBasculaLbl.setText("XXX.XX");
        pesoBasculaLbl.setOpaque(true);

        pesoManualTxt.setBackground(new java.awt.Color(0, 0, 0));
        pesoManualTxt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pesoManualTxt.setForeground(new java.awt.Color(0, 204, 51));
        pesoManualTxt.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        pesoManualTxt.addKeyListener(new NumericKeyListener());

        pesoManualChk.setText("Pesaje Manual");
        pesoManualChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoManualChkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesoBasculaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesoManualTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesoManualChk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pesoBasculaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(pesoManualTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pesoManualChk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pesoManualChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoManualChkActionPerformed
        AbstractButton abstractButton = (AbstractButton) evt.getSource();
        boolean selected = abstractButton.getModel().isSelected();
        if (selected) {
            this.pesoBasculaLbl.setEnabled(false);
            this.pesoManualTxt.setEnabled(true);
        } else {
            this.pesoBasculaLbl.setEnabled(true);
            this.pesoManualTxt.setEnabled(false);
        }
    }//GEN-LAST:event_pesoManualChkActionPerformed

    public BigDecimal getPeso(){
        if (pesoManualChk.isSelected()) {
            if (pesoManualTxt.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe introducir el peso de la caja.");
                return null;
            }
            return (new BigDecimal(pesoManualTxt.getText()));
        } else {
            System.out.println("lalalala "+pesoBasculaLbl.getText());
           return (new BigDecimal(pesoBasculaLbl.getText().trim()));
        }
    }

    public JTextField getPesoManualTxt() {
        return pesoManualTxt;
    }

    public JCheckBox getPesoManualChk() {
        return pesoManualChk;
    }

    public void setPesoManualChk(JCheckBox pesoManualChk) {
        this.pesoManualChk = pesoManualChk;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pesoBasculaLbl;
    private javax.swing.JCheckBox pesoManualChk;
    private javax.swing.JTextField pesoManualTxt;
    // End of variables declaration//GEN-END:variables
}
