/*
-- Query: 
-- Date: 2014-11-09 15:39
*/
INSERT INTO `PRODUCTOS_INVENTARIO` (`CODIGO`,`PESO`,`PRECIO`,`NOTAS_DE_VENTA_CODIGO`,`PRODUCTOS_has_PROVEEDORES_CODIGO`,`ORDENES_COMPRA_CODIGO`,`TRANFERENCIAS_CODIGO`,`CODIGO_BARRAS`,`UBICACIONES_CODIGO`) VALUES (1,25,10,NULL,1,1,NULL,'1234',1);
