
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import dao.ProductoDAO;
import java.awt.Component;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import mapping.ProductosInventario;
import net.sf.click.extras.control.PickList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Karla
 */
public class AbrirProcesoPanel extends javax.swing.JPanel {
    ProductoDAO productoDAO = new ProductoDAO();
    DefaultListModel lmDisponibles =new DefaultListModel();
    DefaultListModel lmSeleccionados =new DefaultListModel();
    /**
     * Creates new form AbrirProcesoPanel
     */
    public AbrirProcesoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        disponiblesJList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        seleccionadosJList = new javax.swing.JList();
        seleccionarSelecBtn = new javax.swing.JButton();
        SeleccionarTodosBtn = new javax.swing.JButton();
        quitarTodosBtn = new javax.swing.JButton();
        quitarSelecBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pesoLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fechaLbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1070, 620));

        jButton1.setText("Abrir proceso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        disponiblesJList.setModel(lmDisponibles);
        try{
            for(Object elemento : productoDAO.getCanalesDisponibles()){
                lmDisponibles.addElement(elemento);
            }
        }catch(Exception e){

        }
        jScrollPane1.setViewportView(disponiblesJList);

        seleccionadosJList.setModel(lmSeleccionados);
        jScrollPane2.setViewportView(seleccionadosJList);

        seleccionarSelecBtn.setText(">");
        seleccionarSelecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarSelecBtnActionPerformed(evt);
            }
        });

        SeleccionarTodosBtn.setText(">>");
        SeleccionarTodosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarTodosBtnActionPerformed(evt);
            }
        });

        quitarTodosBtn.setText("<<");
        quitarTodosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarTodosBtnActionPerformed(evt);
            }
        });

        quitarSelecBtn.setText("<");
        quitarSelecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarSelecBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Producto Disponible");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Producto seleccionado");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Observaciones");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));

        jLabel4.setText("Peso inicial");

        jLabel5.setText("Fecha de apertura");

        pesoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pesoLbl.setText("0");
        pesoLbl.setToolTipText("");

        jLabel7.setText("KG");

        fechaLbl.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pesoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaLbl)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoLbl)
                    .addComponent(jLabel7)
                    .addComponent(fechaLbl))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SeleccionarTodosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quitarTodosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quitarSelecBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(seleccionarSelecBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jButton1)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(seleccionarSelecBtn)
                        .addGap(18, 18, 18)
                        .addComponent(SeleccionarTodosBtn)
                        .addGap(18, 18, 18)
                        .addComponent(quitarTodosBtn)
                        .addGap(18, 18, 18)
                        .addComponent(quitarSelecBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarSelecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarSelecBtnActionPerformed
        int[] indices = disponiblesJList.getSelectedIndices();
        for(int x = indices.length-1 ; x >= 0; x--){
            lmSeleccionados.addElement(lmDisponibles.getElementAt(indices[x]));
            lmDisponibles.removeElementAt(indices[x]);
        }
        actualizarPeso();
    }//GEN-LAST:event_seleccionarSelecBtnActionPerformed

    private void SeleccionarTodosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarTodosBtnActionPerformed
        for(Object element : lmDisponibles.toArray()){
            lmSeleccionados.addElement(element);
        }
        lmDisponibles.clear();
        actualizarPeso();
    }//GEN-LAST:event_SeleccionarTodosBtnActionPerformed

    private void quitarTodosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarTodosBtnActionPerformed
        for(Object element : lmSeleccionados.toArray()){
            lmDisponibles.addElement(element);
        }
        lmSeleccionados.clear();
        actualizarPeso();
    }//GEN-LAST:event_quitarTodosBtnActionPerformed

    private void quitarSelecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarSelecBtnActionPerformed
        int[] indices = seleccionadosJList.getSelectedIndices();
        for(int x = indices.length-1 ; x >= 0; x--){
            lmDisponibles.addElement(lmSeleccionados.getElementAt(indices[x]));
            lmSeleccionados.removeElementAt(indices[x]);
        }
        actualizarPeso();
    }//GEN-LAST:event_quitarSelecBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void actualizarPeso(){
        BigDecimal pesoInicial = new BigDecimal("0.00");
        for (Object producto : lmSeleccionados.toArray()){
            pesoInicial= pesoInicial.add(((ProductosInventario)producto).getPeso());
        }
        pesoLbl.setText(pesoInicial.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SeleccionarTodosBtn;
    private javax.swing.JList disponiblesJList;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel pesoLbl;
    private javax.swing.JButton quitarSelecBtn;
    private javax.swing.JButton quitarTodosBtn;
    private javax.swing.JList seleccionadosJList;
    private javax.swing.JButton seleccionarSelecBtn;
    // End of variables declaration//GEN-END:variables
}
