package com.valco.pojo;
// Generated 2/11/2014 06:06:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * AbonosCuentasXCobrar generated by hbm2java
 */
public class AbonosCuentasXCobrar  implements java.io.Serializable {


     private Integer codigo;
     private CuentasXCobrar cuentasXCobrar;
     private Date fecha;
     private BigDecimal importe;
     private String observaciones;
     private String estatus;
     private Date fechaUltimoAbono;

    public AbonosCuentasXCobrar() {
    }

	
    public AbonosCuentasXCobrar(CuentasXCobrar cuentasXCobrar, Date fecha, String estatus) {
        this.cuentasXCobrar = cuentasXCobrar;
        this.fecha = fecha;
        this.estatus = estatus;
    }
    public AbonosCuentasXCobrar(CuentasXCobrar cuentasXCobrar, Date fecha, BigDecimal importe, String observaciones, String estatus) {
       this.cuentasXCobrar = cuentasXCobrar;
       this.fecha = fecha;
       this.importe = importe;
       this.observaciones = observaciones;
       this.estatus = estatus;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public CuentasXCobrar getCuentasXCobrar() {
        return this.cuentasXCobrar;
    }
    
    public void setCuentasXCobrar(CuentasXCobrar cuentasXCobrar) {
        this.cuentasXCobrar = cuentasXCobrar;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }




}


