package com.valco.pojo;
// Generated 16/03/2015 07:32:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Clientes generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Clientes  implements java.io.Serializable {

    @XmlTransient
     private Integer codigo;
     @XmlAttribute(name = "Nombre")
     private String razonSocial;
     @XmlTransient
     private String apellidoPaterno;
     @XmlTransient
     private String apellidoMaterno;
     @XmlTransient
     private String nombres;
     @XmlTransient
     private String calle;
     @XmlTransient
     private String colonia;
     @XmlTransient
     private String numeroInterior;
     @XmlTransient
     private int numeroExterior;
     @XmlTransient
     private Integer codigoPostal;
     @XmlTransient
     private String ciudad;
     @XmlTransient
     private String estado;
     @XmlTransient
     private String pais;
     @XmlTransient
     private Integer limiteCredito;
     @XmlAttribute(name = "Rfc")
     private String rfc;
     @XmlTransient
     private String correoElectronico;
     @XmlTransient
     private Boolean incobrable;
     @XmlTransient
     private Boolean foreano;
     @XmlTransient
     private String estatus;
     @XmlTransient
     private String cuentaBancaria;
     @XmlTransient
     private String banco;
     @XmlAttribute(name = "UsoCFDI")
     private String usoCFDI;
     @XmlAttribute(name = "RegimenFiscal")
     private String regimenFiscal;
     @XmlTransient
     private Set<NotasDeVenta> notasDeVentas = new HashSet<NotasDeVenta>(0);
     @XmlTransient
     private Set<Telefonos> telefonoses = new HashSet<Telefonos>(0);
     @XmlTransient
     private Set<NotasCredito> notasCreditos = new HashSet<NotasCredito>(0);

    public Clientes() {
    }

	
    public Clientes(String razonSocial, String apellidoPaterno, String nombres, String calle, int numeroExterior, String ciudad, String estado, String pais, String estatus) {
        this.razonSocial = razonSocial;
        this.apellidoPaterno = apellidoPaterno;
        this.nombres = nombres;
        this.calle = calle;
        this.numeroExterior = numeroExterior;
        this.ciudad = ciudad;
        this.estado = estado;
        this.pais = pais;
        this.estatus = estatus;
    }
    public Clientes(String razonSocial, String apellidoPaterno, String apellidoMaterno, String nombres, String calle, String colonia, String numeroInterior, int numeroExterior, Integer codigoPostal, String ciudad, String estado, String pais, Integer limiteCredito, String rfc, String correoElectronico, Boolean incobrable, Boolean foreano, String estatus, String cuentaBancaria, String banco, Set<NotasDeVenta> notasDeVentas) {
       this.razonSocial = razonSocial;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.nombres = nombres;
       this.calle = calle;
       this.colonia = colonia;
       this.numeroInterior = numeroInterior;
       this.numeroExterior = numeroExterior;
       this.codigoPostal = codigoPostal;
       this.ciudad = ciudad;
       this.estado = estado;
       this.pais = pais;
       this.limiteCredito = limiteCredito;
       this.rfc = rfc;
       this.correoElectronico = correoElectronico;
       this.incobrable = incobrable;
       this.foreano = foreano;
       this.estatus = estatus;
       this.cuentaBancaria = cuentaBancaria;
       this.banco = banco;
       this.notasDeVentas = notasDeVentas;
       this.telefonoses = telefonoses;
       this.notasCreditos = notasCreditos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getNumeroInterior() {
        return this.numeroInterior;
    }
    
    public void setNumeroInterior(String numeroInterior) {
        this.numeroInterior = numeroInterior;
    }
    public int getNumeroExterior() {
        return this.numeroExterior;
    }
    
    public void setNumeroExterior(int numeroExterior) {
        this.numeroExterior = numeroExterior;
    }
    public Integer getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Integer getLimiteCredito() {
        return this.limiteCredito;
    }
    
    public void setLimiteCredito(Integer limiteCredito) {
        this.limiteCredito = limiteCredito;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Boolean getIncobrable() {
        return this.incobrable;
    }
    
    public void setIncobrable(Boolean incobrable) {
        this.incobrable = incobrable;
    }
    public Boolean getForeano() {
        return this.foreano;
    }
    
    public void setForeano(Boolean foreano) {
        this.foreano = foreano;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getCuentaBancaria() {
        return this.cuentaBancaria;
    }
    
    public void setCuentaBancaria(String cuentaBancaria) {
        this.cuentaBancaria = cuentaBancaria;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }
    public Set<NotasDeVenta> getNotasDeVentas() {
        return this.notasDeVentas;
    }
    
    public void setNotasDeVentas(Set<NotasDeVenta> notasDeVentas) {
        this.notasDeVentas = notasDeVentas;
    }

    public Set<Telefonos> getTelefonoses() {
        return telefonoses;
    }

    public void setTelefonoses(Set<Telefonos> telefonoses) {
        this.telefonoses = telefonoses;
    }

    public Set<NotasCredito> getNotasCreditos() {
        return notasCreditos;
    }

    public void setNotasCreditos(Set<NotasCredito> notasCreditos) {
        this.notasCreditos = notasCreditos;
    }

    public String getNombreCompleto(){
        return this.getNombres()+" "+this.getApellidoPaterno() +" "+this.getApellidoMaterno();
    }

    public String getUsoCFDI() {
        return usoCFDI;
    }

    public void setUsoCFDI(String usoCFDI) {
        this.usoCFDI = usoCFDI;
    }

    public String getRegimenFiscal() {
        return regimenFiscal;
    }

    public void setRegimenFiscal(String regimenFiscal) {
        this.regimenFiscal = regimenFiscal;
    }
    
    public String toString(){
        return this.getRazonSocial();
    }
    
    public boolean equals(Object o) {
        if( o != null){
        if((o instanceof Clientes) && (((Clientes) o).getCodigo() == this.getCodigo())){
            return true;
        }else{
            return false;
           }
        }else{
            return false;
        }
    }


}


