package com.valco.pojo;
// Generated 8/02/2015 10:57:24 AM by Hibernate Tools 4.3.1

import com.valco.pojo.Facturas;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ConceptosFactura generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class ConceptosFactura implements java.io.Serializable {

    @XmlTransient
    private Integer codigo;
    @XmlTransient
    private Facturas facturas; 
    @XmlAttribute(name="Cantidad")
    private BigDecimal cantidad;
    @XmlAttribute(name="ClaveProdServ")
    private int clave;
    @XmlAttribute(name="Descripcion")
    private String descripcion;
    @XmlAttribute(name="Unidad")
    private String unidad;
    @XmlAttribute(name="ClaveUnidad")
    private String claveUnidad;
    @XmlAttribute(name="ValorUnitario")
    private BigDecimal precioUnitario;
    @XmlAttribute(name="Importe")
    private BigDecimal importeTotal;
    @XmlAttribute(name="Descuento")
    private BigDecimal descuento;
    @XmlTransient
    private String claveProducto;
    @XmlElement(namespace = "http://www.sat.gob.mx/cfd/3", name="Impuestos")
    private Impuesto impuesto;

    public ConceptosFactura() {
    }

    public ConceptosFactura(Facturas facturas, BigDecimal cantidad, int clave, String descripcion, String unidad, BigDecimal precioUnitario, BigDecimal importeTotal) {
        this.facturas = facturas;
        this.cantidad = cantidad;
        this.clave = clave;
        this.descripcion = descripcion;
        this.unidad = unidad;
        this.precioUnitario = precioUnitario;
        this.importeTotal = importeTotal;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public Facturas getFacturas() {
        return this.facturas;
    }

    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }

    public BigDecimal getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    public int getClave() {
        return this.clave;
    }

    public void setClave(int clave) {
        this.clave = clave;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getUnidad() {
        return this.unidad;
    }

    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }

    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }

    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }

    public BigDecimal getImporteTotal() {
        return this.importeTotal;
    }

    public void setImporteTotal(BigDecimal importeTotal) {
        this.importeTotal = importeTotal;
    }

    public String getClaveProducto() {
        return claveProducto;
    }

    public void setClaveProducto(String claveProducto) {
        this.claveProducto = claveProducto;
    }

    public String getClaveUnidad() {
        return claveUnidad;
    }

    public void setClaveUnidad(String claveUnidad) {
        this.claveUnidad = claveUnidad;
    }

    public BigDecimal getDescuento() {
        return descuento;
    }

    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    public Impuesto getImpuesto() {
        return impuesto;
    }

    public void setImpuesto(Impuesto impuesto) {
        this.impuesto = impuesto;
    }
    
    
    
    

    public boolean equals(Object o) {
        if (o != null) {
            if ((o instanceof ConceptosFactura) && (((ConceptosFactura) o).getCodigo()== this.getCodigo())) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
    
   
    
    

}
