package com.valco.pojo;
// Generated 12/10/2015 09:38:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Devoluciones generated by hbm2java
 */
public class Devoluciones  implements java.io.Serializable {


     private Integer codigo;
     private BigDecimal peso;
     private Boolean devolucionTotal;
     private ProductosInventario productosInventario;
     private NotasCredito notasCredito;

    public Devoluciones() {
    }

	
    public Devoluciones(ProductosInventario productosInventario, NotasCredito notasCreditoCodigo) {
        this.productosInventario = productosInventario;
        this.notasCredito = notasCreditoCodigo;
    }
    public Devoluciones(BigDecimal peso, Boolean devolucionTotal, ProductosInventario productosInventario, NotasCredito notasCredito) {
       this.peso = peso;
       this.devolucionTotal = devolucionTotal;
       this.productosInventario = productosInventario;
       this.notasCredito = notasCredito;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public BigDecimal getPeso() {
        return this.peso;
    }
    
    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }
    public Boolean getDevolucionTotal() {
        return this.devolucionTotal;
    }
    
    public void setDevolucionTotal(Boolean devolucionTotal) {
        this.devolucionTotal = devolucionTotal;
    }

    public ProductosInventario getProductosInventario() {
        return productosInventario;
    }

    public void setProductosInventario(ProductosInventario productosInventario) {
        this.productosInventario = productosInventario;
    }

    public NotasCredito getNotasCredito() {
        return notasCredito;
    }

    public void setNotasCredito(NotasCredito notasCredito) {
        this.notasCredito = notasCredito;
    }
   




}


