package com.valco.pojo;
// Generated 16/03/2015 07:32:10 PM by Hibernate Tools 4.3.1

import com.valco.beans.CFDIRelacionado;
import com.valco.beans.CFDIRelacionados;
import com.valco.utility.DateAdapter;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Facturas generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(namespace = "http://www.sat.gob.mx/cfd/3", name = "Comprobante")
public class Facturas implements java.io.Serializable {

    @XmlTransient
    private Integer codigo;
    @XmlTransient
    private NotasDeVenta notasDeVenta;
    @XmlAttribute(name = "LugarExpedicion")
    private String lugar;
    @XmlAttribute(name = "Fecha")
    @XmlJavaTypeAdapter(DateAdapter.class)
    private Date fecha;
    @XmlAttribute(name = "Folio")
    private int folio;
    @XmlTransient
    private String folioFiscal;
    @XmlTransient
    private Date fechaTimbrado;
    @XmlTransient
    private String noSerieCertSat;
    @XmlTransient
    private String observaciones;
    @XmlTransient
    private String estatus;
    @XmlTransient
    private String xml;
    @XmlAttribute(name = "FormaPago")
    private String formaPago;
    @XmlAttribute(name = "NoCertificado")
    private String noSeieCertEmisor;
    @XmlAttribute(name = "MetodoPago")
    private String metodoPago;
    @XmlAttribute(name = "Moneda")
    private String moneda;
    @XmlTransient
    private int noCliente;
    @XmlTransient
    private String banco;
    @XmlAttribute(name = "SubTotal")
    private BigDecimal subtotal;
    @XmlAttribute(name = "Descuento")
    private BigDecimal descuento;
    @XmlTransient
    private BigDecimal iva;
    @XmlAttribute(name = "Total")
    private BigDecimal total;
    @XmlTransient
    private String importeLetra;
    @XmlAttribute(name = "Sello")
    private String selloCdfi;
    @XmlTransient
    private String selloSat;
    @XmlTransient
    private String cadenaOriginal;
    @XmlTransient
    private String cadenaCompromiso;
    @XmlAttribute(name = "CondicionesDePago")
    private String condicionPago;
    @XmlAttribute(name = "Serie")
    private String serie;
    @XmlAttribute(name = "TipoDeComprobante")
    private String tipoDocumento;
    @XmlAttribute(name = "TipoCambio")
    private String tipoCambio;
    @XmlTransient
    private String usoCFDI;
    @XmlAttribute(name = "Version")
    private String version;
    @XmlAttribute(name = "Certificado")
    private String certificado;
    @XmlElement(namespace = "http://www.sat.gob.mx/cfd/3", name="CfdiRelacionados")
    private CFDIRelacionados cfdiRelacionados;
    @XmlElement(name = "Emisor", namespace = "http://www.sat.gob.mx/cfd/3")
    private Clientes emisor;
    @XmlElement(name = "Receptor", namespace = "http://www.sat.gob.mx/cfd/3")
    private Clientes receptor;
    @XmlTransient
    private List<ConceptosFactura> conceptos;
    @XmlElement(name = "Complemento", namespace = "http://www.sat.gob.mx/cfd/3")
    public Complemento complemento;
    @XmlTransient
    private Set<NotasDeVenta> notasDeVentas = new HashSet<NotasDeVenta>(0);
    @XmlElementWrapper(namespace = "http://www.sat.gob.mx/cfd/3", name = "Conceptos")
    @XmlElement(name = "Concepto", namespace = "http://www.sat.gob.mx/cfd/3")
    private Set<ConceptosFactura> conceptosFacturas = new HashSet<ConceptosFactura>(0);
    @XmlTransient
    private Set<Impuestos> impuestoses = new HashSet<Impuestos>(0);
    @XmlElement(namespace = "http://www.sat.gob.mx/cfd/3", name="Impuestos")
    private Impuesto impuesto;

    public Facturas() {
    }

    public Facturas(NotasDeVenta notasDeVenta, String lugar, Date fecha, int folio, String folioFiscal, Date fechaTimbrado, String noSerieCertSat, String estatus, String xml, String formaPago, String noSeieCertEmisor, String metodoPago, String moneda, int noCliente, String banco, BigDecimal subtotal, BigDecimal iva, BigDecimal total, String selloCdfi, String selloSat, String cadenaOriginal, String condicionPago) {
        this.notasDeVenta = notasDeVenta;
        this.lugar = lugar;
        this.fecha = fecha;
        this.folio = folio;
        this.folioFiscal = folioFiscal;
        this.fechaTimbrado = fechaTimbrado;
        this.noSerieCertSat = noSerieCertSat;
        this.estatus = estatus;
        this.xml = xml;
        this.formaPago = formaPago;
        this.noSeieCertEmisor = noSeieCertEmisor;
        this.metodoPago = metodoPago;
        this.moneda = moneda;
        this.noCliente = noCliente;
        this.banco = banco;
        this.subtotal = subtotal;
        this.iva = iva;
        this.total = total;
        this.selloCdfi = selloCdfi;
        this.selloSat = selloSat;
        this.cadenaOriginal = cadenaOriginal;
        this.condicionPago = condicionPago;
    }

    public Facturas(NotasDeVenta notasDeVenta, String lugar, Date fecha, int folio, String folioFiscal, Date fechaTimbrado, String noSerieCertSat, String observaciones, String estatus, String xml, String formaPago, String noSeieCertEmisor, String metodoPago, String moneda, int noCliente, String banco, BigDecimal subtotal, BigDecimal iva, BigDecimal total, String importeLetra, String selloCdfi, String selloSat, String cadenaOriginal, String cadenaCompromiso, String condicionPago, String serie, Set<NotasDeVenta> notasDeVentas, Set<ConceptosFactura> conceptosFacturas) {
        this.notasDeVenta = notasDeVenta;
        this.lugar = lugar;
        this.fecha = fecha;
        this.folio = folio;
        this.folioFiscal = folioFiscal;
        this.fechaTimbrado = fechaTimbrado;
        this.noSerieCertSat = noSerieCertSat;
        this.observaciones = observaciones;
        this.estatus = estatus;
        this.xml = xml;
        this.formaPago = formaPago;
        this.noSeieCertEmisor = noSeieCertEmisor;
        this.metodoPago = metodoPago;
        this.moneda = moneda;
        this.noCliente = noCliente;
        this.banco = banco;
        this.subtotal = subtotal;
        this.iva = iva;
        this.total = total;
        this.importeLetra = importeLetra;
        this.selloCdfi = selloCdfi;
        this.selloSat = selloSat;
        this.cadenaOriginal = cadenaOriginal;
        this.cadenaCompromiso = cadenaCompromiso;
        this.condicionPago = condicionPago;
        this.serie = serie;
        this.notasDeVentas = notasDeVentas;
        this.conceptosFacturas = conceptosFacturas;
        this.impuestoses = impuestoses;
    }

    public Facturas getNotaDeCredito() {
        Facturas notaDeCredito = new Facturas();

        notaDeCredito.setLugar(this.lugar);
        notaDeCredito.setFecha(new Date());
        notaDeCredito.setFolio(this.folio);
        notaDeCredito.setFechaTimbrado(new Date());
        notaDeCredito.setEstatus("ACTIVO");
        notaDeCredito.setFormaPago(this.formaPago);
        notaDeCredito.setMetodoPago(this.metodoPago);
        notaDeCredito.setMoneda(this.moneda);
        notaDeCredito.setNoCliente(this.noCliente);
        notaDeCredito.setBanco(this.banco);
        notaDeCredito.setCadenaCompromiso(this.cadenaCompromiso);
        notaDeCredito.setCondicionPago(this.condicionPago);
        notaDeCredito.setSerie("NC");
        notaDeCredito.setNotasDeVenta(notasDeVenta);
        return notaDeCredito;

    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public NotasDeVenta getNotasDeVenta() {
        return this.notasDeVenta;
    }

    public void setNotasDeVenta(NotasDeVenta notasDeVenta) {
        this.notasDeVenta = notasDeVenta;
    }

    public String getLugar() {
        return this.lugar;
    }

    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public int getFolio() {
        return this.folio;
    }

    public void setFolio(int folio) {
        this.folio = folio;
    }

    public String getFolioFiscal() {
        return this.folioFiscal;
    }

    public void setFolioFiscal(String folioFiscal) {
        this.folioFiscal = folioFiscal;
    }

    public Date getFechaTimbrado() {
        return this.fechaTimbrado;
    }

    public void setFechaTimbrado(Date fechaTimbrado) {
        this.fechaTimbrado = fechaTimbrado;
    }

    public String getNoSerieCertSat() {
        return this.noSerieCertSat;
    }

    public void setNoSerieCertSat(String noSerieCertSat) {
        this.noSerieCertSat = noSerieCertSat;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public String getEstatus() {
        return this.estatus;
    }

    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    public String getXml() {
        return this.xml;
    }

    public void setXml(String xml) {
        this.xml = xml;
    }

    public String getFormaPago() {
        return this.formaPago;
    }

    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }

    public String getNoSeieCertEmisor() {
        return this.noSeieCertEmisor;
    }

    public void setNoSeieCertEmisor(String noSeieCertEmisor) {
        this.noSeieCertEmisor = noSeieCertEmisor;
    }

    public String getMetodoPago() {
        return this.metodoPago;
    }

    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }

    public String getMoneda() {
        return this.moneda;
    }

    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    public int getNoCliente() {
        return this.noCliente;
    }

    public void setNoCliente(int noCliente) {
        this.noCliente = noCliente;
    }

    public String getBanco() {
        return this.banco;
    }

    public void setBanco(String banco) {
        this.banco = banco;
    }

    public BigDecimal getSubtotal() {
        return this.subtotal;
    }

    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    public BigDecimal getIva() {
        return this.iva;
    }

    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }

    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public String getImporteLetra() {
        return this.importeLetra;
    }

    public void setImporteLetra(String importeLetra) {
        this.importeLetra = importeLetra;
    }

    public String getSelloCdfi() {
        return this.selloCdfi;
    }

    public void setSelloCdfi(String selloCdfi) {
        this.selloCdfi = selloCdfi;
    }

    public String getSelloSat() {
        return this.selloSat;
    }

    public void setSelloSat(String selloSat) {
        this.selloSat = selloSat;
    }

    public String getCadenaOriginal() {
        return this.cadenaOriginal;
    }

    public void setCadenaOriginal(String cadenaOriginal) {
        this.cadenaOriginal = cadenaOriginal;
    }

    public String getCadenaCompromiso() {
        return this.cadenaCompromiso;
    }

    public void setCadenaCompromiso(String cadenaCompromiso) {
        this.cadenaCompromiso = cadenaCompromiso;
    }

    public String getCondicionPago() {
        return this.condicionPago;
    }

    public void setCondicionPago(String condicionPago) {
        this.condicionPago = condicionPago;
    }

    public String getSerie() {
        return this.serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public Set<NotasDeVenta> getNotasDeVentas() {
        return this.notasDeVentas;
    }

    public void setNotasDeVentas(Set<NotasDeVenta> notasDeVentas) {
        this.notasDeVentas = notasDeVentas;
    }

    public Set<ConceptosFactura> getConceptosFacturas() {
        return this.conceptosFacturas;
    }

    public void setConceptosFacturas(Set<ConceptosFactura> conceptosFacturas) {
        this.conceptosFacturas = conceptosFacturas;
    }

    public Set<Impuestos> getImpuestoses() {
        return this.impuestoses;
    }

    public void setImpuestoses(Set<Impuestos> impuestoses) {
        this.impuestoses = impuestoses;
    }

    public String getTipoDocumento() {
        return tipoDocumento;
    }

    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    public String getUsoCFDI() {
        return usoCFDI;
    }

    public void setUsoCFDI(String usoCFDI) {
        this.usoCFDI = usoCFDI;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getCertificado() {
        return certificado;
    }

    public void setCertificado(String certificado) {
        this.certificado = certificado;
    }

    public Clientes getEmisor() {
        return emisor;
    }

    public void setEmisor(Clientes emisor) {
        this.emisor = emisor;
    }

    public Clientes getReceptor() {
        return receptor;
    }

    public void setReceptor(Clientes receptor) {
        this.receptor = receptor;
    }

    public List<ConceptosFactura> getConceptos() {
        return conceptos;
    }

    public void setConceptos(List<ConceptosFactura> conceptos) {
        this.conceptos = conceptos;
    }

    public Complemento getComplemento() {
        return complemento;
    }

    public void setComplemento(Complemento complemento) {
        this.complemento = complemento;
    }

    public BigDecimal getDescuento() {
        return descuento;
    }

    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    public String getTipoCambio() {
        return tipoCambio;
    }

    public void setTipoCambio(String tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    public CFDIRelacionados getCfdiRelacionados() {
        return cfdiRelacionados;
    }

    public void setCfdiRelacionados(CFDIRelacionados cfdiRelacionados) {
        this.cfdiRelacionados = cfdiRelacionados;
    }

    public Impuesto getImpuesto() {
        return impuesto;
    }

    public void setImpuesto(Impuesto impuesto) {
        this.impuesto = impuesto;
    }
    

    @Override
    public boolean equals(Object o) {
        if (o != null) {
            if ((o instanceof Facturas) && (((Facturas) o).getCodigo().equals(this.getCodigo()))) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

}
