package com.valco.pojo;
// Generated 2/11/2014 06:06:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private Integer codigo;
     private Date fecha;
     private BigDecimal subtotal;
     private BigDecimal iva;
     private BigDecimal total;
     private String observaciones;
     private String estatus;
     private String xml;
     private String formaPago;
     private Set<NotasDeVenta> notasDeVentas = new HashSet<NotasDeVenta>(0);

    public Facturas() {
    }

	
    public Facturas(Date fecha, BigDecimal subtotal, BigDecimal iva, BigDecimal total, String estatus) {
        this.fecha = fecha;
        this.subtotal = subtotal;
        this.iva = iva;
        this.total = total;
        this.estatus = estatus;
    }
    public Facturas(Date fecha, BigDecimal subtotal, BigDecimal iva, BigDecimal total, String observaciones, String estatus, Set<NotasDeVenta> notasDeVentas) {
       this.fecha = fecha;
       this.subtotal = subtotal;
       this.iva = iva;
       this.total = total;
       this.observaciones = observaciones;
       this.estatus = estatus;
       this.notasDeVentas = notasDeVentas;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public Set<NotasDeVenta> getNotasDeVentas() {
        return this.notasDeVentas;
    }
    
    public void setNotasDeVentas(Set<NotasDeVenta> notasDeVentas) {
        this.notasDeVentas = notasDeVentas;
    }

    public String getXml() {
        return xml;
    }

    public void setXml(String xml) {
        this.xml = xml;
    }

    public String getFormaPago() {
        return formaPago;
    }

    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }

    


}


