package com.valco.pojo;
// Generated 15/03/2015 09:49:32 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;

/**
 * Impuestos generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Impuestos  implements java.io.Serializable {


     private Integer codigo;
     private Facturas facturas;
     @XmlAttribute(name="Base")
     private BigDecimal base;
     @XmlAttribute(name="Impuesto")
     private String impuesto;
     @XmlAttribute(name="TipoFactor")
     private String tipoFactor;
     @XmlAttribute(name="TasaOCuota")
     private BigDecimal tasa;
     @XmlAttribute(name="Importe")
     private BigDecimal importe;

    public Impuestos() {
    }

    public Impuestos(Facturas facturas, String impuesto, BigDecimal tasa, BigDecimal importe) {
       this.facturas = facturas;
       this.impuesto = impuesto;
       this.tasa = tasa;
       this.importe = importe;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Facturas getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }
    public String getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(String impuesto) {
        this.impuesto = impuesto;
    }
    public BigDecimal getTasa() {
        return this.tasa;
    }
    
    public void setTasa(BigDecimal tasa) {
        this.tasa = tasa;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }

    public BigDecimal getBase() {
        return base;
    }

    public void setBase(BigDecimal base) {
        this.base = base;
    }

    public String getTipoFactor() {
        return tipoFactor;
    }

    public void setTipoFactor(String tipoFactor) {
        this.tipoFactor = tipoFactor;
    }
    
    
}


