package com.valco.pojo;
// Generated 2/11/2014 06:06:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubicaciones generated by hbm2java
 */
public class Ubicaciones  implements java.io.Serializable {


     private Integer codigo;
     private String estado;
     private String ciudad;
     private String oficina;
     private String estatus;
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);
     private Set<ProductosInventario> productosInventarios = new HashSet<ProductosInventario>(0);
     private Set<Tranferencias> tranferenciasesForSalida = new HashSet<Tranferencias>(0);
     private Set<Tranferencias> tranferenciasesForDestino = new HashSet<Tranferencias>(0);

    public Ubicaciones() {
    }

	
    public Ubicaciones(String estado, String ciudad, String oficina, String estatus) {
        this.estado = estado;
        this.ciudad = ciudad;
        this.oficina = oficina;
        this.estatus = estatus;
    }
    public Ubicaciones(String estado, String ciudad, String oficina, String estatus, Set<Usuarios> usuarioses, Set<ProductosInventario> productosInventarios, Set<Tranferencias> tranferenciasesForSalida, Set<Tranferencias> tranferenciasesForDestino) {
       this.estado = estado;
       this.ciudad = ciudad;
       this.oficina = oficina;
       this.estatus = estatus;
       this.usuarioses = usuarioses;
       this.productosInventarios = productosInventarios;
       this.tranferenciasesForSalida = tranferenciasesForSalida;
       this.tranferenciasesForDestino = tranferenciasesForDestino;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getOficina() {
        return this.oficina;
    }
    
    public void setOficina(String oficina) {
        this.oficina = oficina;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set<ProductosInventario> getProductosInventarios() {
        return this.productosInventarios;
    }
    
    public void setProductosInventarios(Set<ProductosInventario> productosInventarios) {
        this.productosInventarios = productosInventarios;
    }
    public Set<Tranferencias> getTranferenciasesForSalida() {
        return this.tranferenciasesForSalida;
    }
    
    public void setTranferenciasesForSalida(Set<Tranferencias> tranferenciasesForSalida) {
        this.tranferenciasesForSalida = tranferenciasesForSalida;
    }
    public Set<Tranferencias> getTranferenciasesForDestino() {
        return this.tranferenciasesForDestino;
    }
    
    public void setTranferenciasesForDestino(Set<Tranferencias> tranferenciasesForDestino) {
        this.tranferenciasesForDestino = tranferenciasesForDestino;
    }




}


